site_name: market-lead-scoring-propensity-modeling2
repo_url: https://github.com/hantablack9/market-lead-scoring-propensity-modeling2
site_url: https://hantablack9.github.io/market-lead-scoring-propensity-modeling2
site_description: This is a project to deliver a machine learning model which qualifies leads for the sales department of an ed-tech platform.
site_author: Hanish Paturi
edit_uri: edit/main/docs/
repo_name: hantablack9/market-lead-scoring-propensity-modeling2
copyright: Maintained by <a href="https://hantablack9.com">hantablack9</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/lead_scoring"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hantablack9/market-lead-scoring-propensity-modeling2
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/market-lead-scoring-propensity-modeling2

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
